DEFAULT_CATEGORY_TAXONOMY = [
    {
        "name": "Income",
        "slug": "income",
        "children": [
            {"name": "Salary", "slug": "income-salary"},
            {"name": "Refund", "slug": "income-refund"},
            {"name": "Investment Income", "slug": "income-investment-income"},
        ],
    },
    {
        "name": "Food",
        "slug": "food",
        "children": [
            {"name": "Dining", "slug": "food-dining"},
            {"name": "Takeout", "slug": "food-takeout"},
        ],
    },
    {
        "name": "Groceries",
        "slug": "groceries",
        "children": [],
    },
    {
        "name": "Shopping",
        "slug": "shopping",
        "children": [],
    },
    {
        "name": "Transportation",
        "slug": "transportation",
        "children": [
            {"name": "Uber / Rideshare", "slug": "transportation-uber-rideshare"},
            {"name": "Parking & Tolls", "slug": "transportation-parking-tolls"},
        ],
    },
    {
        "name": "Car Related",
        "slug": "car-related",
        "children": [
            {"name": "Car Payment", "slug": "car-related-car-payment"},
            {"name": "Gas", "slug": "car-related-gas"},
            {"name": "Insurance", "slug": "car-related-insurance"},
            {"name": "Maintenance", "slug": "car-related-maintenance"},
            {"name": "Other", "slug": "car-related-other"},
        ],
    },
    {
        "name": "Subscriptions / Bills",
        "slug": "subscriptions-bills",
        "children": [
            {"name": "Credit Card Payment", "slug": "subscriptions-bills-credit-card-payment"},
            {"name": "Phone", "slug": "subscriptions-bills-phone"},
            {"name": "Internet", "slug": "subscriptions-bills-internet"},
            {"name": "Streaming", "slug": "subscriptions-bills-streaming"},
            {"name": "Memberships", "slug": "subscriptions-bills-memberships"},
            {"name": "Loans", "slug": "subscriptions-bills-loans"},
            {"name": "Other Bills", "slug": "subscriptions-bills-other-bills"},
        ],
    },
    {
        "name": "Savings",
        "slug": "savings",
        "children": [],
    },
    {
        "name": "Travel",
        "slug": "travel",
        "children": [
            {"name": "Flights", "slug": "travel-flights"},
            {"name": "Hotel", "slug": "travel-hotel"},
            {"name": "Travel Fees", "slug": "travel-fees"},
        ],
    },
    {
        "name": "Entertainment",
        "slug": "entertainment",
        "children": [
            {"name": "Events", "slug": "entertainment-events"},
            {"name": "Movies", "slug": "entertainment-movies"},
            {"name": "Games", "slug": "entertainment-games"},
        ],
    },
    {
        "name": "Health",
        "slug": "health",
        "children": [],
    },
    {
        "name": "Housing",
        "slug": "housing",
        "children": [
            {"name": "Rent / Mortgage", "slug": "housing-rent-mortgage"},
            {"name": "HOA", "slug": "housing-hoa"},
            {"name": "Property Tax", "slug": "housing-property-tax"},
            {"name": "Home Insurance", "slug": "housing-home-insurance"},
            {"name": "Maintenance", "slug": "housing-maintenance"},
        ],
    },
    {
        "name": "Utilities",
        "slug": "utilities",
        "children": [
            {"name": "Electric", "slug": "utilities-electric"},
            {"name": "Water", "slug": "utilities-water"},
            {"name": "Gas (home)", "slug": "utilities-gas-home"},
            {"name": "Trash", "slug": "utilities-trash"},
            {"name": "Sewer", "slug": "utilities-sewer"},
        ],
    },
    {
        "name": "Other",
        "slug": "other",
        "children": [],
    },
]


DEFAULT_SYSTEM_RULES = [
    {"rule_type": "contains", "pattern": "starbucks", "category": "Food", "subcategory": "Dining", "priority": 980, "confidence": 0.95, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "dunkin", "category": "Food", "subcategory": "Dining", "priority": 975, "confidence": 0.95, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "mcdonald", "category": "Food", "subcategory": "Takeout", "priority": 970, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "chipotle", "category": "Food", "subcategory": "Takeout", "priority": 970, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "uber eats", "category": "Food", "subcategory": "Takeout", "priority": 968, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "doordash", "category": "Food", "subcategory": "Takeout", "priority": 968, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "grubhub", "category": "Food", "subcategory": "Takeout", "priority": 968, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "shoprite", "category": "Groceries", "subcategory": "", "priority": 960, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "whole foods", "category": "Groceries", "subcategory": "", "priority": 960, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "trader joe", "category": "Groceries", "subcategory": "", "priority": 960, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "costco", "category": "Groceries", "subcategory": "", "priority": 955, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "aldi", "category": "Groceries", "subcategory": "", "priority": 955, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "walmart grocery", "category": "Groceries", "subcategory": "", "priority": 955, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "amazon", "category": "Shopping", "subcategory": "", "priority": 930, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "target", "category": "Shopping", "subcategory": "", "priority": 930, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "best buy", "category": "Shopping", "subcategory": "", "priority": 930, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "ebay", "category": "Shopping", "subcategory": "", "priority": 928, "confidence": 0.86, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "etsy", "category": "Shopping", "subcategory": "", "priority": 928, "confidence": 0.86, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "uber", "category": "Transportation", "subcategory": "Uber / Rideshare", "priority": 950, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "lyft", "category": "Transportation", "subcategory": "Uber / Rideshare", "priority": 950, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "nj transit", "category": "Transportation", "subcategory": "", "priority": 950, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "amtrak", "category": "Transportation", "subcategory": "", "priority": 950, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "ezpass", "category": "Transportation", "subcategory": "Parking & Tolls", "priority": 950, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "shell", "category": "Car Related", "subcategory": "Gas", "priority": 945, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "exxon", "category": "Car Related", "subcategory": "Gas", "priority": 945, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "bp", "category": "Car Related", "subcategory": "Gas", "priority": 944, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "wawa", "category": "Car Related", "subcategory": "Gas", "priority": 944, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "sunoco", "category": "Car Related", "subcategory": "Gas", "priority": 944, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "delta", "category": "Travel", "subcategory": "Flights", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "united", "category": "Travel", "subcategory": "Flights", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "american airlines", "category": "Travel", "subcategory": "Flights", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "hilton", "category": "Travel", "subcategory": "Hotel", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "marriott", "category": "Travel", "subcategory": "Hotel", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "hyatt", "category": "Travel", "subcategory": "Hotel", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "airbnb", "category": "Travel", "subcategory": "Hotel", "priority": 940, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "netflix", "category": "Subscriptions / Bills", "subcategory": "Streaming", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "spotify", "category": "Subscriptions / Bills", "subcategory": "Streaming", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "apple com bill", "category": "Subscriptions / Bills", "subcategory": "Other Bills", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "youtube premium", "category": "Subscriptions / Bills", "subcategory": "Streaming", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "amazon prime", "category": "Subscriptions / Bills", "subcategory": "Memberships", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "chatgpt", "category": "Subscriptions / Bills", "subcategory": "Memberships", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "payroll", "category": "Income", "subcategory": "Salary", "priority": 995, "confidence": 0.95, "subtype": "income"},
    {"rule_type": "contains", "pattern": "direct dep", "category": "Income", "subcategory": "Salary", "priority": 995, "confidence": 0.95, "subtype": "income"},
    {"rule_type": "contains", "pattern": "adp", "category": "Income", "subcategory": "Salary", "priority": 995, "confidence": 0.93, "subtype": "income"},
    {"rule_type": "contains", "pattern": "paychex", "category": "Income", "subcategory": "Salary", "priority": 995, "confidence": 0.93, "subtype": "income"},
    {"rule_type": "contains", "pattern": "payment thank you", "category": "Subscriptions / Bills", "subcategory": "Credit Card Payment", "priority": 999, "confidence": 0.95, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "online payment", "category": "Subscriptions / Bills", "subcategory": "Credit Card Payment", "priority": 998, "confidence": 0.92, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "capital one mobile payment", "category": "Subscriptions / Bills", "subcategory": "Credit Card Payment", "priority": 998, "confidence": 0.95, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "capital one payment", "category": "Subscriptions / Bills", "subcategory": "Credit Card Payment", "priority": 998, "confidence": 0.95, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "autopay payment", "category": "Subscriptions / Bills", "subcategory": "Credit Card Payment", "priority": 998, "confidence": 0.95, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "transfer", "category": "Other", "subcategory": "", "priority": 992, "confidence": 0.85, "subtype": "transfer"},
    {"rule_type": "contains", "pattern": "zelle", "category": "Other", "subcategory": "", "priority": 992, "confidence": 0.85, "subtype": "transfer"},
    {"rule_type": "contains", "pattern": "venmo cashout", "category": "Other", "subcategory": "", "priority": 992, "confidence": 0.9, "subtype": "transfer"},
    {"rule_type": "contains", "pattern": "ach transfer", "category": "Other", "subcategory": "", "priority": 992, "confidence": 0.88, "subtype": "transfer"},
]
