DEFAULT_CATEGORY_TAXONOMY = [
    {
        "name": "Income",
        "slug": "income",
        "children": [
            {"name": "Salary", "slug": "income-salary"},
            {"name": "Bonus", "slug": "income-bonus"},
            {"name": "Refund", "slug": "income-refund"},
            {"name": "Investment Income", "slug": "income-investment-income"},
        ],
    },
    {
        "name": "Transfer",
        "slug": "transfer",
        "children": [],
    },
    {
        "name": "Credit Card Payment",
        "slug": "credit-card-payment",
        "children": [],
    },
    {
        "name": "Dining",
        "slug": "dining",
        "children": [
            {"name": "Restaurants", "slug": "dining-restaurants"},
            {"name": "Coffee", "slug": "dining-coffee"},
            {"name": "Bars", "slug": "dining-bars"},
        ],
    },
    {
        "name": "Groceries",
        "slug": "groceries",
        "children": [],
    },
    {
        "name": "Transportation",
        "slug": "transportation",
        "children": [
            {"name": "Uber/Taxi", "slug": "transportation-uber-taxi"},
            {"name": "Public Transit", "slug": "transportation-public-transit"},
            {"name": "Parking & Tolls", "slug": "transportation-parking-tolls"},
            {"name": "Car Maintenance", "slug": "transportation-car-maintenance"},
        ],
    },
    {
        "name": "Gas",
        "slug": "gas",
        "children": [],
    },
    {
        "name": "Shopping",
        "slug": "shopping",
        "children": [
            {"name": "Clothing", "slug": "shopping-clothing"},
            {"name": "Electronics", "slug": "shopping-electronics"},
            {"name": "General Shopping", "slug": "shopping-general-shopping"},
        ],
    },
    {
        "name": "Housing",
        "slug": "housing",
        "children": [],
    },
    {
        "name": "Utilities",
        "slug": "utilities",
        "children": [
            {"name": "Electric", "slug": "utilities-electric"},
            {"name": "Water", "slug": "utilities-water"},
            {"name": "Internet", "slug": "utilities-internet"},
            {"name": "Phone", "slug": "utilities-phone"},
        ],
    },
    {
        "name": "Health",
        "slug": "health",
        "children": [
            {"name": "Doctor", "slug": "health-doctor"},
            {"name": "Pharmacy", "slug": "health-pharmacy"},
            {"name": "Insurance", "slug": "health-insurance"},
        ],
    },
    {
        "name": "Subscriptions",
        "slug": "subscriptions",
        "children": [],
    },
    {
        "name": "Entertainment",
        "slug": "entertainment",
        "children": [],
    },
    {
        "name": "Savings",
        "slug": "savings",
        "children": [],
    },
    {
        "name": "Travel",
        "slug": "travel",
        "children": [
            {"name": "Flights", "slug": "travel-flights"},
            {"name": "Hotels", "slug": "travel-hotels"},
            {"name": "Vacation", "slug": "travel-vacation"},
            {"name": "Travel Fees", "slug": "travel-fees"},
        ],
    },
    {
        "name": "Fees",
        "slug": "fees",
        "children": [],
    },
    {
        "name": "Cash Withdrawal",
        "slug": "cash-withdrawal",
        "children": [],
    },
    {
        "name": "Needs Review",
        "slug": "needs-review",
        "children": [],
    },
    {
        "name": "Other",
        "slug": "other",
        "children": [],
    },
]


DEFAULT_SYSTEM_RULES = [
    {"rule_type": "contains", "pattern": "starbucks", "category": "Dining", "subcategory": "Coffee", "priority": 980, "confidence": 0.95, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "dunkin", "category": "Dining", "subcategory": "Coffee", "priority": 975, "confidence": 0.95, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "mcdonald", "category": "Dining", "subcategory": "Restaurants", "priority": 970, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "chipotle", "category": "Dining", "subcategory": "Restaurants", "priority": 970, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "uber eats", "category": "Dining", "subcategory": "Restaurants", "priority": 968, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "doordash", "category": "Dining", "subcategory": "Restaurants", "priority": 968, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "grubhub", "category": "Dining", "subcategory": "Restaurants", "priority": 968, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "shoprite", "category": "Groceries", "subcategory": "", "priority": 960, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "whole foods", "category": "Groceries", "subcategory": "", "priority": 960, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "trader joe", "category": "Groceries", "subcategory": "", "priority": 960, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "costco", "category": "Groceries", "subcategory": "", "priority": 955, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "aldi", "category": "Groceries", "subcategory": "", "priority": 955, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "walmart grocery", "category": "Groceries", "subcategory": "", "priority": 955, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "uber", "category": "Transportation", "subcategory": "Uber/Taxi", "priority": 950, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "lyft", "category": "Transportation", "subcategory": "Uber/Taxi", "priority": 950, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "nj transit", "category": "Transportation", "subcategory": "Public Transit", "priority": 950, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "amtrak", "category": "Transportation", "subcategory": "Public Transit", "priority": 950, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "ezpass", "category": "Transportation", "subcategory": "Parking & Tolls", "priority": 950, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "shell", "category": "Gas", "subcategory": "", "priority": 945, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "exxon", "category": "Gas", "subcategory": "", "priority": 945, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "bp", "category": "Gas", "subcategory": "", "priority": 944, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "wawa", "category": "Gas", "subcategory": "", "priority": 944, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "sunoco", "category": "Gas", "subcategory": "", "priority": 944, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "delta", "category": "Travel", "subcategory": "Flights", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "united", "category": "Travel", "subcategory": "Flights", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "american airlines", "category": "Travel", "subcategory": "Flights", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "hilton", "category": "Travel", "subcategory": "Hotels", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "marriott", "category": "Travel", "subcategory": "Hotels", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "hyatt", "category": "Travel", "subcategory": "Hotels", "priority": 940, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "airbnb", "category": "Travel", "subcategory": "Vacation", "priority": 940, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "netflix", "category": "Subscriptions", "subcategory": "", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "spotify", "category": "Subscriptions", "subcategory": "", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "apple com bill", "category": "Subscriptions", "subcategory": "", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "youtube premium", "category": "Subscriptions", "subcategory": "", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "amazon prime", "category": "Subscriptions", "subcategory": "", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "chatgpt", "category": "Subscriptions", "subcategory": "", "priority": 938, "confidence": 0.92, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "amazon", "category": "Shopping", "subcategory": "General Shopping", "priority": 930, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "target", "category": "Shopping", "subcategory": "General Shopping", "priority": 930, "confidence": 0.88, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "best buy", "category": "Shopping", "subcategory": "Electronics", "priority": 930, "confidence": 0.9, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "ebay", "category": "Shopping", "subcategory": "General Shopping", "priority": 928, "confidence": 0.86, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "etsy", "category": "Shopping", "subcategory": "General Shopping", "priority": 928, "confidence": 0.86, "subtype": "expense"},
    {"rule_type": "contains", "pattern": "payroll", "category": "Income", "subcategory": "Salary", "priority": 995, "confidence": 0.95, "subtype": "income"},
    {"rule_type": "contains", "pattern": "direct dep", "category": "Income", "subcategory": "Salary", "priority": 995, "confidence": 0.95, "subtype": "income"},
    {"rule_type": "contains", "pattern": "adp", "category": "Income", "subcategory": "Salary", "priority": 995, "confidence": 0.93, "subtype": "income"},
    {"rule_type": "contains", "pattern": "paychex", "category": "Income", "subcategory": "Salary", "priority": 995, "confidence": 0.93, "subtype": "income"},
    {"rule_type": "contains", "pattern": "payment thank you", "category": "Credit Card Payment", "subcategory": "", "priority": 999, "confidence": 0.95, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "online payment", "category": "Credit Card Payment", "subcategory": "", "priority": 998, "confidence": 0.92, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "capital one mobile payment", "category": "Credit Card Payment", "subcategory": "", "priority": 998, "confidence": 0.95, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "capital one payment", "category": "Credit Card Payment", "subcategory": "", "priority": 998, "confidence": 0.95, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "autopay payment", "category": "Credit Card Payment", "subcategory": "", "priority": 998, "confidence": 0.95, "subtype": "payment"},
    {"rule_type": "contains", "pattern": "transfer", "category": "Transfer", "subcategory": "", "priority": 992, "confidence": 0.85, "subtype": "transfer"},
    {"rule_type": "contains", "pattern": "zelle", "category": "Transfer", "subcategory": "", "priority": 992, "confidence": 0.85, "subtype": "transfer"},
    {"rule_type": "contains", "pattern": "venmo cashout", "category": "Transfer", "subcategory": "", "priority": 992, "confidence": 0.9, "subtype": "transfer"},
    {"rule_type": "contains", "pattern": "ach transfer", "category": "Transfer", "subcategory": "", "priority": 992, "confidence": 0.88, "subtype": "transfer"},
]
